apiVersion: gremlin.kubedex.com/v1alpha1
kind: Gremlin
metadata:
  name: example-gremlin
spec:
  team_id: ""
  type: attack-container
  gremlin: memory
  length: 60
  gigabytes: 1GB
  megabytes: 2MB
  percent: 10