apiVersion: gremlin.kubedex.com/v1alpha1
kind: Gremlin
metadata:
  name: example-process-killer-gremlin
spec:
  team_id: ''
  type: attack-container
  gremlin: process_killer
  interval: 60
  process: '^abc'
  signal: -9
  group: adm
  user: user
  newest: true
  oldest: false
  exact: true
  kill_children: true
  full: false