apiVersion: gremlin.kubedex.com/v1alpha1
kind: Gremlin
metadata:
  name: example-disk-gremlin
spec:
  team_id: ""
  type: attack-container
  gremlin: disk
  length: 60
  dir: /tmp
  workers: 1
  block_size: 1
  percent: 1