apiVersion: gremlin.kubedex.com/v1alpha1
kind: Gremlin
metadata:
  name: example-memory-gremlin
spec:
  team_id: ""
  type: attack-container
  gremlin: memory
  length: 60
  gigabytes: 1
  megabytes: 2
  percent: 10