apiVersion: gremlin.kubedex.com/v1alpha1
kind: Gremlin
metadata:
  name: example-gremlin
spec:
  team_id: ""
  type: attack-container
  gremlin: latency
  length: 60
  ms: 60
  device: ecth0
  egress_port: 443
  src_port: 443
  ipaddress: 192.168.1.1
  hostname: example.com
  ipprotocol: tcp